config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :welcomes, :only => :index
  resources :orcamentos
  resources :pedidos
  resources :produtos
  resources :pessoas
  resources :forma_pagamentos
  resources :tipo_forma_pagamentos

  devise_for :users, :controllers => { registrations: 'registrations' }

  root :to => 'welcomes#index'

end

app/models/orcamento.rb
class Orcamento < ActiveRecord::Base
  belongs_to :cliente, class_name: 'Pessoa'
  belongs_to :vendedor, class_name: 'Pessoa'
  has_many :orcamento_produtos, :inverse_of => :orcamento
  has_many :produtos, :through => :orcamento_produtos
  has_many :orcamento_forma_pagamentos, :inverse_of => :orcamento

  accepts_nested_attributes_for :orcamento_produtos, :allow_destroy => true
  accepts_nested_attributes_for :orcamento_forma_pagamentos, :allow_destroy => true

  validates :cliente, presence: true
  validates :vendedor, presence: true
  validates :orcamento_produtos, presence: true


  before_save :update_total

  def to_s
    pessoa.nm_pessoa
  end

  rails_admin do
    navigation_label 'Financeiro'
    list do
      field :id
      field :cliente
      field :vendedor
      field :created_at
      field :vl_total
    end
    edit do
      field :cliente do
        associated_collection_cache_all false
        associated_collection_scope do
          orcamento = bindings[:object]
          Proc.new { |scope| scope = scope.where(tipo_pessoa_id: 1)
          }
        end
      end
      field :vendedor do
        associated_collection_cache_all false
        associated_collection_scope do
          orcamento = bindings[:object]
          Proc.new { |scope| scope = scope.where(tipo_pessoa_id: 2)
          }
        end
      end
      field :orcamento_produtos
      field :orcamento_forma_pagamentos
    end
  end

  private
  def update_total
    self.vl_total = orcamento_produtos.map(&:calc_sub_total).sum
  end
end

app/controllers/orcamentos_controller.rb
class OrcamentosController < ApplicationController
  before_action :authenticate_user!

  def index
    @orcamentos = Orcamento.all
  end

  def show
    @orcamento = Orcamento.find(params[:id])
  end

  def new
    @orcamento = Orcamento.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @orcamento }
    end
  end

  def create
    @orcamento = Orcamento.new(orcamento_params)
    respond_to do |format|
      if @orcamento.save
        format.html { redirect_to @orcamento, notice: 'Orçamento Criado com Sucesso.' }
        format.json { render json: @orcamento, status: :created, location: @orcamento }
      else
        format.html { render action: "new" }
        format.json { render json: @orcamento.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  def orcamento_params
    params.require(:orcamento).permit(:cliente_id, :vendedor_id, :vl_total,
                                      orcamento_produtos_attributes:
                                      [:id, :produto_id, :qt_produto, :sub_total, :_destroy])
  end
end

app/views/orcamentos/_form.html.erb
  <%= simple_form_for(@orcamento) do |f| %>

  <div class="form-inputs">
    <div class="row">
      <div class="col-md-3">
        <%= f.input :cliente_id, input_html: { data: { source: pessoas_path(tipo: 1),
          init_id: @orcamento.cliente_id,
          init_ds: @orcamento.cliente.try(:name)
        }
      } %>
      </div>

      <div class="col-md-3">
        <%= f.input :vendedor_id, input_html: { data: { source: pessoas_path(tipo: 2),
          init_id: @orcamento.vendedor_id,
          init_ds: @orcamento.vendedor.try(:name)
        }
      } %>
      </div>
    </div><br/>

    <h4>Produtos</h4><br/>
    <div class="row">
      <div class="col-md-3">Produto</div>
      <div class="col-md-2">Quantidade</div>
      <div class="col-md-2">Valor unitário</div>
      <hr class="line title-product"/>
    </div>

    <div class="row" id="orcamento_produtos">
      <%= f.simple_fields_for :orcamento_produtos do |item| %>
      <%= render 'orcamento_produto_fields', :f => item  %><br/>
      <%end%>
    </div><br/>

    <div class=" row">
      <%= link_to_add_association 'Adicionar Produto', f, :orcamento_produtos, :class => "btn btn-default" %>
      <%= f.button :submit, :class => "btn btn-primary"  %>
    </div><br/>
  </div>
<%end%>

<script type="text/javascript">
  loadSelect2($('#orcamento_cliente_id'));
  loadSelect2($('#orcamento_vendedor_id'));
</script>

app/views/orcamentos/_orcamento_produto_fields.html.erb
<div class="nested-fields">
  <div class="row">
    <div class="col-md-3">
      <%= f.input :produto_id, label: false,
      input_html: { class: 'product-select2',
        data: { source: produtos_path,
          init_id: f.object.produto_id,
          init_ds: f.object.produto.try(:name)
        }
      } %>
    </div>

    <div class="col-md-2">
      <%= f.input :qt_produto, label: false %>
    </div>

    <div class="col-md-2">
      <%= f.input :sub_total, label: false, as: :string, input_html: {class: 'currency'} %>
    </div>

    <div class="col-md-2">
      <%= link_to_remove_association "Remover Produto", f, :class => "btn btn-danger btn-sm" %>
    </div>
  </div>
  <hr class="line"/>

  <script type="text/javascript">
  loadSelect2($('.product-select2').last());
  loadMasks();
  </script>
</div>

app/views/orcamentos/index.html.erb
<h1>Lista de Orçamentos</h1>

<table class="table table-bordered table-striped table-hover">
  <thead>
    <tr>
      <th width=200>Número do orçamento</th>
      <th width=400>Cliente</th>
      <th>CPF/CNPJ</th>
      <th>Vendedor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orcamentos.each do |orcamentos| %>
      <tr>
        <td><%= orcamentos.id %></td>
        <td><%= orcamentos.cliente.nm_pessoa %></td>
        <td><%= orcamentos.cliente.nr_cpfcnpj %></td>
        <td><%= orcamentos.vendedor.nm_pessoa %></td>
        <td><%= link_to 'Visualizar', orcamentos %></td>
        <td><%= link_to 'Editar', edit_orcamento_path(orcamentos) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Novo', new_orcamento_path %>

app/views/orcamentos/new.html.erb
<h1>Novo Orçamento</h1>

<% if @orcamento.errors.present? %>
<div class="alert alert-warning">
  <%= @orcamento.errors.full_messages.join('<br/>').html_safe %>
</div>
<% end %>

<%= render 'form' %>

app/views/orcamentos/show.html.erb
  <div class="numero">
    <h4>
    Número do orçamento: <%= @orcamento.id %>
    </h4><br/>
  </div>

  <h4>Dados do Cliente:</h4>
  <table class="table table-bordered table-striped table-hover table-condensed" id="dados">
    <thead>
      <tr>
        <th width=300>Nome: <%= @orcamento.cliente.nm_pessoa %></th>
        <th width=300>Fantasia: <%= @orcamento.cliente.nm_fantasia %></th>
        <th width=200>CPF/CNPJ: <%= @orcamento.cliente.nr_cpfcnpj %></th>
        <th width=250>E-mail: <%= @orcamento.cliente.email_pessoa %></th>
      </tr>
    </thead>
  </table>
  <table class="table table-bordered table-striped table-hover table-condensed" id="pessoa">
    <thead>
      <tr>
        <th width=800>Endereço: <%= @orcamento.cliente.end_rua %></th>
        <th width=250>Número: <%= @orcamento.cliente.end_numero %></th>
      </tr>
    </thead>
  </table>
  <table class="table table-bordered table-striped table-hover table-condensed" id="endereco">
    <thead>
      <tr>
        <th width=250>Bairro: <%= @orcamento.cliente.end_bairro %></th>
        <th width=100>Cep: <%= @orcamento.cliente.end_cep %></th>
        <th width=250>Complemento: <%= @orcamento.cliente.end_complemento %></th>
      </tr>
    </thead>
  </table>

  <h4>Produtos:</h4>

  <table class="table table-hover">
    <thead>
      <tr>
        <th>Produto</th>
        <th>Quantidade</th>
        <th>Valor Unitário</th>
        <th>Total</th>
      </tr>
    </thead>

    <tbody>
      <% @orcamento.orcamento_produtos.each do |orcamentoproduto| %>
      <tr>
        <td><%= orcamentoproduto.produto.ds_produto %></td>
        <td><%= orcamentoproduto.qt_produto %></td>
        <td><%= orcamentoproduto.sub_total %></td>
        <td><%= orcamentoproduto.qt_produto * orcamentoproduto.sub_total   %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <div class="valor-total">
    <h4>
      Valor Total: <%= @orcamento.vl_total %>
    </h4>
  </div>

  <%= link_to 'Back', orcamentos_path %>