config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'

  resources :welcomes, :only => :index
  resources :orcamentos
  resources :pedidos
  resources :produtos
  resources :pessoas
  resources :forma_pagamentos
  resources :tipo_forma_pagamentos

  devise_for :users, :controllers => { registrations: 'registrations' }

  root :to => 'welcomes#index'

end

app/models/pedido.rb
class Pedido < ActiveRecord::Base
  belongs_to :cliente, class_name: 'Pessoa'
  belongs_to :vendedor, class_name: 'Pessoa'
  belongs_to :movimento_estoque_produto
  belongs_to :forma_pagamento, :inverse_of => :pedido

  has_many :conta_recebers, :inverse_of => :pedido
  has_many :pedido_produtos, :inverse_of => :pedido
  has_many :produtos, :through => :pedido_produtos

  accepts_nested_attributes_for :pedido_produtos, :allow_destroy => true
  accepts_nested_attributes_for :conta_recebers, :allow_destroy => true

  validates :cliente, presence: true
  validates :vendedor, presence: true

  before_save :update_total
  after_save :create_parcelas!

  def name
    id.to_s + " - " + cliente.nm_pessoa
  end

  private
  def update_total
    self.vl_total = pedido_produtos.map(&:calc_sub_total).sum
  end

  def create_parcelas!
    vl_parcela_pedido = (self.vl_total / self.forma_pagamento.qt_pagamento).round
    mes = 0
    for i in 1..self.forma_pagamento.qt_pagamento
      c = ContaReceber.new pedido_id: self.id, vl_conta: vl_parcela_pedido
      if i == 1
        c.dt_vencimento = Date.today
        if !self.forma_pagamento.possui_entrada
          c.dt_vencimento = c.dt_vencimento.change(day: self.forma_pagamento.dia_pagamento)
          c.dt_vencimento = c.dt_vencimento + (i).month
        end
      else
        c.dt_vencimento = Date.today
        c.dt_vencimento = c.dt_vencimento.change(day: self.forma_pagamento.dia_pagamento)
        if self.forma_pagamento.possui_entrada
          c.dt_vencimento = c.dt_vencimento + (i-1).month
        else
          c.dt_vencimento = c.dt_vencimento + (i).month
        end
      end
      c.save
    end
  end

  rails_admin do
    navigation_label 'Financeiro'
    list do
      field :id
      field :cliente
      field :vendedor
      field :created_at
      field :vl_total
    end
    edit do
      field :cliente do
        associated_collection_cache_all false
        associated_collection_scope do
          pedido = bindings[:object]
          Proc.new { |scope| scope = scope.where(tipo_pessoa_id: 1)
          }
        end
      end
      field :vendedor do
        associated_collection_cache_all false
        associated_collection_scope do
          pedido = bindings[:object]
          Proc.new { |scope| scope = scope.where(tipo_pessoa_id: 2)
          }
        end
      end
      field :pedido_produtos
      field :forma_pagamento
      field :conta_recebers
    end
  end
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :authenticate_user!
  def index
    @pedidos = Pedido.all
  end

  def show
    @pedido = Pedido.find(params[:id])
  end

  def new
    @pedido = Pedido.new(forma_pagamento: FormaPagamento.new)
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pedido }
    end
  end

  def edit
    @pedido = Pedido.find(params[:id])
  end

  def create
    @pedido = Pedido.new(pedido_params)
    respond_to do |format|
      if @pedido.save
        format.html { redirect_to @pedido, notice: 'Shopping list was successfully created.' }
      else
        format.html { render action: "new" }
      end
    end
  end

  private
  def pedido_params
    params.require(:pedido).permit(:cliente_id, :vendedor_id, :vl_total,
      pedido_produtos_attributes:
      [:id, :produto_id, :qt_produto, :sub_total, :_destroy])
  end
end

app/views/pedidos/_form.html.slim
= simple_form_for(@pedido) do |f|
  div class="form-inputs"
    div class="row"
      div class="col-md-3"
        = f.input :cliente_id, input_html: { class: 'select2', data: { source: pessoas_path(tipo: 1),
          init_id: @pedido.cliente_id,
          init_ds: @pedido.cliente.try(:name)}}
      div class="col-md-3"
        = f.input :vendedor_id, input_html: { class: 'select2',  data: { source: pessoas_path(tipo: 2),
          init_id: @pedido.vendedor_id,
          init_ds: @pedido.vendedor.try(:name)}}
    br

    ul.nav.nav-tabs role='tablist'
      li.active
        = link_to 'Produtos', '#produtos', data: {toggle: 'tab'}
      li
        = link_to 'Forma de Pagamento', '#forma', data: {toggle: 'tab'}
      br/

    .tab-content
      #produtos.tab-pane.active role='tabpanel'
        br/
        div class="row"
          div class="col-md-3"Produto
          div class="col-md-2"Quantidade
          div class="col-md-2"Valor unitário
          hr class="line title-product"

        = f.simple_fields_for :pedido_produtos do |item|
          = render 'pedido_produto_fields', :f => item
        .links
          = link_to_add_association 'Adicionar Produto', f, :pedido_produtos, :class => "btn btn-default"
        br/

      #forma.tab-pane.active role='tabpanel'
        br/
        div class="row"
          = f.simple_fields_for :forma_pagamento do |forma|

            div class="col-md-3"
              = f.input :forma_pagamento_id, input_html: { class: 'select_forma',  data: { source: forma_pagamentos_path,
                init_id: @pedido.forma_pagamento_id,
                init_ds: @pedido.forma_pagamento.try(:name)}}

            div class="col-md-2"
              = forma.input :qt_pagamento

            div class="col-md-2"
              = forma.input :dia_pagamento

            div class="col-md-2"
              = forma.input :possui_entrada, as: :boolean, inline_label: true, label: false
        br/

    .actions
      = f.button :submit, :class => "btn btn-primary"

  javascript:
    loadSelect2($('#pedido_cliente_id'));
    loadSelect2($('#pedido_vendedor_id'));
    loadSelect2($('.select_forma'));

app/views/pedidos/_pedido_produto_fields.html.slim
div class="nested-fields"
  div class="row"
    div class="col-md-3"
      = f.input :produto_id, label: false,
      input_html: { class: 'productselect2', data: { source: produtos_path,
          init_id: f.object.produto_id,
          init_ds: f.object.produto.try(:name)}}

    div class="col-md-2"
      = f.input :qt_produto, label: false

    div class="col-md-2"
      = f.input :sub_total, label: false, as: :string, input_html: {class: 'currency'}

    div class="col-md-2"
      = link_to_remove_association "Remover Produto", f, :class => "btn btn-danger btn-sm"
  hr class="line"

  javascript:
    loadSelect2($('.productselect2').last());
    loadMasks();

app/views/pedidos/edit.html.slim
h1
 |Editar Pedido

= render 'form'

app/views/pedidos/index.html.slim
h1
  Lista Pedido de Vendas

table class="table table-bordered table-striped table-hover"
  thead
    tr
      th width='200'
        |Número pedido de venda
      th width='400'
        |Cliente
      th
        |CPF/CNPJ
      th
        |Vendedor
      th colspan="3"
      -@pedidos.each do |pedidos|
        tr
          td= pedidos.id
          td= pedidos.cliente.nm_pessoa
          td= pedidos.cliente.nr_cpfcnpj
          td= pedidos.vendedor.nm_pessoa
          td width='150'
            = link_to 'Visualizar', pedidos, class: 'btn btn-info btn-xs'
            = ' '
            = link_to 'Editar', edit_pedido_path(pedidos), class: 'btn btn-primary btn-xs'
br/
= link_to 'Novo', new_pedido_path, class: 'btn btn-primary btn-xs'

app/views/pedidos/new.html.slim
h1
  | Novo Pedido de Venda

-if @pedido.errors.present?
  .div class="alert alert-warning"
    = @pedido.errors.full_messages.join('<br/>').html_safe

= render 'form'

app/views/pedidos/show.html.slim
.numero
  h4
    | Número pedido de venda:
    = @pedido.id
  br/
h4 Dados do Cliente:
table#dados.table.table-bordered.table-striped.table-hover.table-condensed
  thead
    tr
      th width="300"
        |Nome: #{@pedido.cliente.nm_pessoa}
      th width="300"
        |Fantasia/Sobrenome: #{@pedido.cliente.nm_fantasia}
      th width="200"
        |CPF/CNPJ: #{@pedido.cliente.nr_cpfcnpj}
      th width="250"
        |E-mail: #{@pedido.cliente.email_pessoa}
table#pessoa.table.table-bordered.table-striped.table-hover.table-condensed
  thead
    tr
      th width="800"
        |Endereço: #{@pedido.cliente.end_rua}
      th width="250"
        |Número: #{@pedido.cliente.end_numero}
table#endereco.table.table-bordered.table-striped.table-hover.table-condensed
  thead
    tr
      th width="250"
        |Bairro: #{@pedido.cliente.end_bairro}
      th width="100"
        |Cep: #{@pedido.cliente.end_cep}
      th width="250"
        |Complemento: #{@pedido.cliente.end_complemento}
h4 Produtos:
table.table.table-hover
  tr
    th Produto
    th Quantidade
    th Valor Unitário
    th Total
    -@pedido.pedido_produtos.each do |pedidoproduto|
      tr
        td= pedidoproduto.produto.ds_produto
        td= pedidoproduto.qt_produto
        td= pedidoproduto.sub_total
        td= pedidoproduto.qt_produto * pedidoproduto.sub_total
.valor-total
  h4
    | Valor Total:
    = @pedido.vl_total
= link_to 'Back', pedidos_path